Fix configure.ac
On arch linux, this project did not compile due to 

  CC       libpal_la-palDfltin.lo
palDfltin.c: In function 'palDfltin':
palDfltin.c:185:3: error: implicit declaration of function 'strlcpy'; did you mean 'strncpy'? [-Wimplicit-function-declaration]
  185 |   strlcpy( tempbuf, &(string[*nstrt-1]), sizeof(tempbuf) );
      |   ^~~~~~~
      |   strncpy

After some debugging, the issue seems that HAVE_BSD_STRING_H was never set and thus the include never happens.